server:
  port: 8888
spring:
  application:
    name: movie-config-server
  cloud:
    config:
      server:
        # git远程仓库
        # 访问url:  /{application}/{profile} eg: /movie-config-server/dev
        git:
          uri: https://github.com/humingk/douban_movie_config/
          search-paths: config
      label: master
    # 总线
    bus:
      enabled: true
      trace:
        # 开启跟踪总线
        enabled: true
  # 消息中间件rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoint:
    bus-refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        # 暴露接口
        include: bus-refresh