server:
  port: 8888
spring:
  application:
    name: movie-config-server
  cloud:
    config:
      server:
        # git远程仓库
        # 访问url:  /{application}/{profile} eg: /movie-service-common/dev
        git:
          uri: https://github.com/humingk/douban_movie_config
          search-paths: config
      label: master