language: java
jdk:
  - openjdk8
cache:
  directories:
    - '$HOME/.m2/repository'
install: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true
script:
  - "mvn compile"
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)