language: java
install: true
jdk:
  - oraclejdk8
script:
  - gradle check
  - gradle build --scan -s
  - gradle codeCoverageReport
after_success:
  - codecov
  - bash bash <(curl -s https://codecov.io/bash) -t f7fdfa04-4055-4179-97f8-432854676f23
