server:
  port: 10101
spring:
  application:
    name: movie-server-movie
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1233
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      client-id: client
      client-secret: client
      # 密码模式需要用到的获取token接口
      access-token-uri: http://localhost:8006/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:8006/oauth/token_key
        key-value: youaretheappleofmyeyes
#       此服务端接收到客户端的请求（包含token）后，通过此接口到认证服务器做token验证
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
