server:
  port: 10101
spring:
  application:
    name: movie-server-movie
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1233
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    resource:
      id: movie-server-movie
      # 用户信息地址
      user-info-uri: http://localhost:8006/user
      prefer-token-info: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
