server:
  port: 8762
spring:
  application:
    name: movie-service-user
  zipkin:
    base-url: http://localhost:9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/