# 项目基础配置
# 自定义全局变量
custom:
  redis:
    # redis缓存过期时间 /d
    expire: 30
  api:
    # api的版本
    version: v2
  jwt:
    key:
      value: youaretheappleofmyeyes
  oauth2:
    # 有效期 s
    validity: 7776000
    # 客户端
    client:
      id: client
      secret: client
      scopes: all
# feign超时设置
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

