# 项目基础配置
# 自定义全局变量
custom:
  redis:
    # redis缓存过期时间 /d
    expire: 30
  api:
    # api的版本
    version: v2
  oauth2:
    # 有效期 s
    validity: 7776000
    # 客户端
    client:
      id: client
      secret: client
      scopes: all
    key:
      # 别名
      alias: oauth2
      # oauth2.jks 绝对路径
      location: /home/humingk/gits/douban_movie_plus/doc/key/oauth2.jks
      # 秘钥口令和秘钥库口令
      secret: 12331233
# feign超时设置
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

