server:
  port: 10103
security:
  oauth2:
    resource:
      # 资源服务器ID
      id: user
spring:
  security:
    oauth2:
      client:
        registration:
          auth:
            client-id: client
            client-secret: client
            client-scopes: all
          github:
            client-id: e97fedfabcf648c19043
            client-secret: 4f6091870ca0e51b432587b557f6375732d3ac44
            # 获取Github授权验证码
            authorize-uri: https://github.com/login/oauth/authorize
            # 获取授权码后回调
            callback-uri: http://localhost:10103/github_callback
            # 通过Github授权验证码和客户端密钥获取token
            access-token-uri: https://github.com/login/oauth/access_token
            # Github用户信息
            user-uri: https://api.github.com/user
