mybatis:
  mapper-locations: classpath:mapper/**/*.xml
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1233
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    hikari:
      # 池中最大连接数，包括闲置和使用中的连接,默认10
      maximumPoolSize: 30
      # 池中维护的最小空闲连接数，默认10
      minimumIdle: 10
      # 连接允许在池中闲置的最长时间，默认600000
      idleTimeout: 600000
      # 等待来自池的连接的最大毫秒数,默认30000
      connectionTimeout: 30000
      # 池中连接最长生命周期，默认1800000
      maxLifetime: 1800000
