custom:
  redis:
    # redis缓存过期时间 /d
    expire: 100
spring:
  redis:
    # Redis数据库索引
    database: 0
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: 1233
    # 连接超时时间（毫秒）
    timeout: 5000
    # 采用默认的lettuce而不是jedis
    lettuce:
      pool:
        #连接池最大连接数 默认8 （使用负值表示没有限制）
        max-active: 32
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池最大阻塞等待时间 默认-1 （使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最小空闲连接 默认0
        min-idle: 0