spring:
  # zipkin服务追踪
  zipkin:
    #    base-url: http://localhost:9411
    sender:
      # 发送类型（rabbit,web）
      type: rabbit
  sleuth:
    web:
      enabled: true
    sampler:
      # zipkin 采样比例,1.0表示采集所有（默认0.1）
      probability: 1.0
