server:
  port: 8086
spring:
  application:
    name: movie-service-api
  cloud:
    gateway:
      discovery:
        locator:
          # true:开启gateway服务注册中心服务发现,并且gateway根据服务名自动为每个服务创建一个router
          # 通过服务名路径访问,eg: http://localhost:8086/MOVIE-SERVICE-COMMON/...
          enabled: false
          # true:请求路径服务名配置为小写
          lower-case-service-id: true
      # 路由转发
      routes:
        - id: movie-service-common
          # common服务负载均衡地址
          uri: lb://movie-service-common
          predicates:
            - Path=/common/**
          filters:
            # 转发前去掉/common/
            - StripPrefix=1
            # 限流过滤器
            # 令牌桶限流算法，当请求拿到桶中的令牌的时候，才能执行
            # 相对于普通桶算法，可以抵挡瞬时的多个请求
            - name: RequestRateLimiter
              args:
                # 用于限流的键的解析器Bean
                key-resolver: '#{@myHostAddrKeyResolver}'
                # 令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                # 令牌桶总容量
                redis-rate-limiter.burstCapacity: 5
        - id: movie-service-douban
          uri: lb://movie-service-douban
          predicates:
            - Path=/douban/**
          filters:
            - StripPrefix=1
  redis:
    # Redis数据库索引
    database: 1
    # Redis服务器地址
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码
    password: 1233
    # 连接超时时间（毫秒）
    timeout: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# gateway日志等级，转发信息
logging:
  level:
    org.springframework.cloud.gateway: info
