debug: true
logging:
  level:
    # 日志记录级别
    root: debug
    tk:
      mybatis:
        springboot:
          mapper: debug
server:
  port: 11111
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1233
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
# mybatis
mybatis:
  check-config-location: false
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: org.humingk.movie.entity
