server:
  port: 8006
spring:
  application:
    name: movie-server-auth
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 1233
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
